name: Deploy CQT Api Gateway Production

on:
  push:
    branches:
      - main
    paths:
      - 'services/api/**'


jobs:
  build-staging:
    uses: ./.github/workflows/main.yml
    with:
      id_api_gateway: 
      environment: 
      region:
      path_contract: ./services/api/cqt-gateway.yml