name: Deploy CQT Api Gateway Stagging

on:
  push:
    branches:
      - main
    paths:
      - 'services/api/**'


jobs:
  build-staging:
    uses: ./.github/workflows/main.yml
    with:
      id_api_gateway: gdfadlnscj
      environment: stagging
      region: us-east-2
      path_contract: ./services/api/cqt-gateway.yml